# Generated by Django 3.1.1 on 2020-10-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mask',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='mask',
            name='without_mask',
            field=models.IntegerField(default=0),
        ),
    ]
