# Generated by Django 3.1.1 on 2020-10-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20201003_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='mask',
            name='date_time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='mask',
            name='day_week',
            field=models.CharField(default='', max_length=50),
        ),
    ]
