# Generated by Django 3.1.1 on 2020-11-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20201003_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='mask',
            name='age',
            field=models.CharField(default='', max_length=20),
        ),
    ]
